import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { styleText } from "node:util";
import path from "path";
import prompts from "prompts";
import { contentHash, writeConfig, type BeaketConfig } from "./config.ts";
import { collapseContext, diffLines } from "./diff.ts";
import { backupFile } from "./files.ts";

const THEME_START = "/* beaket:theme:start */";
const THEME_END = "/* beaket:theme:end */";
const THEME_HEADER =
  "/* DO NOT EDIT — regenerated by 'npx @beaket/ui theme'. Put overrides after the end marker. */";
const OVERRIDES = `
/* beaket:overrides — this section is yours and is never regenerated.
   Match the selectors below: plain :root loses to the generated dark selectors.
   Replace the commented values with your brand colors; keep contrast readable. */
:root, :root[data-theme="light"], :root:not([data-theme]) {
  /* --signal-accent: your-light-brand-color; */
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    /* --signal-accent: your-dark-brand-color; */
  }
}
:root[data-theme="dark"] {
  /* --signal-accent: your-dark-brand-color; */
}
`;

export function wrapThemeCss(css: string): string {
  return `${THEME_START}\n${THEME_HEADER}\n${css.trimEnd()}\n${THEME_END}\n`;
}

export function replaceThemeInCss(
  existingCss: string,
  newThemeCss: string,
): { css: string; replaced: boolean } {
  const wrapped = wrapThemeCss(newThemeCss);
  const stub = existingCss.includes("beaket:overrides") ? "" : OVERRIDES;

  // Try marker-based replacement first
  const startIdx = existingCss.indexOf(THEME_START);
  const endIdx = existingCss.indexOf(THEME_END);

  if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
    const before = existingCss.substring(0, startIdx);
    const afterEnd = endIdx + THEME_END.length;
    // Skip trailing newline after end marker
    const after =
      existingCss[afterEnd] === "\n"
        ? existingCss.substring(afterEnd + 1)
        : existingCss.substring(afterEnd);
    return { css: before + wrapped + stub + after, replaced: true };
  }

  // No existing theme — append
  const separator = existingCss.endsWith("\n") ? "\n" : "\n\n";
  return { css: existingCss + separator + wrapped + stub, replaced: false };
}

export function extractThemeBlock(cssContent: string): string | null {
  const startIdx = cssContent.indexOf(THEME_START);
  const endIdx = cssContent.indexOf(THEME_END);

  if (startIdx !== -1 && endIdx !== -1 && startIdx < endIdx) {
    const contentStart = startIdx + THEME_START.length;
    // Skip leading newline after start marker
    const adjustedStart = cssContent[contentStart] === "\n" ? contentStart + 1 : contentStart;
    return cssContent.substring(adjustedStart, endIdx);
  }

  return null;
}

interface SyncThemeOptions {
  overwrite?: boolean;
  diff?: boolean;
  dryRun?: boolean;
}

export async function syncTheme(
  config: BeaketConfig,
  themeCssMap: Record<string, string>,
  options: SyncThemeOptions = {},
): Promise<boolean> {
  const themeName = config.theme || "solace";
  const themeCss = themeCssMap[themeName];

  if (!themeCss) {
    console.log(styleText("yellow", "!"), `Unknown theme "${themeName}". Skipping theme sync.`);
    return false;
  }

  if (!config.css) {
    console.log(styleText("yellow", "!"), "No CSS path in config. Skipping theme sync.");
    console.log("  Run", styleText("cyan", "npx @beaket/ui init"), "to set CSS path.");
    return false;
  }

  const cssPath = path.join(process.cwd(), config.css);

  if (!existsSync(cssPath)) {
    console.log(
      styleText("yellow", "!"),
      `CSS file not found: ${config.css}. Skipping theme sync.`,
    );
    return false;
  }

  const existingCss = await readFile(cssPath, "utf-8");
  const existingTheme = extractThemeBlock(existingCss);
  const nextTheme = extractThemeBlock(wrapThemeCss(themeCss))!;
  const edited = config.themeHash && contentHash(existingTheme ?? "") !== config.themeHash;
  if (edited) console.log(styleText("yellow", "!"), "Managed theme block has local edits.");

  if (options.diff || options.dryRun) {
    console.log(`Preview ${themeName} theme in ${config.css}; no files will be changed.`);
    if (options.diff) {
      for (const line of collapseContext(diffLines(existingTheme ?? "", nextTheme))) {
        console.log(
          `${line.type === "add" ? "+" : line.type === "remove" ? "-" : " "} ${line.text}`,
        );
      }
    }
    return false;
  }

  async function recordTheme() {
    config.themeHash = contentHash(nextTheme);
    await writeConfig(config);
  }

  // Check if theme is already up to date
  if (existingTheme === nextTheme) {
    await recordTheme();
    console.log(styleText("green", "✔"), "Theme tokens are up to date.");
    return true;
  }

  if (existingTheme === null) {
    // No theme block found — always inject
    const { css } = replaceThemeInCss(existingCss, themeCss);
    await writeFile(cssPath, css);
    await recordTheme();
    console.log(styleText("green", "✔"), `Added ${themeName} theme tokens to ${config.css}`);
    return true;
  }

  // Theme exists but is outdated
  if (!options.overwrite) {
    const { confirm } = await prompts({
      type: "confirm",
      name: "confirm",
      message: `Replace theme tokens in ${config.css} with ${themeName}? Local token edits will be replaced (a backup is saved).`,
      initial: false,
    });
    if (!confirm) {
      console.log(styleText("yellow", "ℹ"), "Skipped theme update.");
      return false;
    }
  }

  const { css } = replaceThemeInCss(existingCss, themeCss);
  await backupFile(cssPath);
  await writeFile(cssPath, css);
  await recordTheme();
  console.log(styleText("green", "✔"), `Updated ${themeName} theme tokens in ${config.css}`);
  return true;
}
