name: Upload Chromatic
permissions:
  contents: read
  statuses: write
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".storybook/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vite.config.ts"
      - "tsconfig.json"
  pull_request:
    paths:
      - "src/**"
      - ".storybook/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "vite.config.ts"
      - "tsconfig.json"

jobs:
  chromatic:
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0 # Required for Chromatic to compare with baseline

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        timeout-minutes: 2

      - name: Run Chromatic tests
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          autoAcceptChanges: "main"
          onlyChanged: true
